openapi: 3.0.1
info:
  description: |
    This documentation allows managing web security services.
    
    Web Security API base url: https://api.___serverHost___/security
    
    # Authentication
    You can find the available authorization methods in this section: <a href="https://api.___serverHost___/docs/iam#section/Authentication">Authorization methods</a>

  title: Web Security API
  version: "1.0.0"

servers:
- url: https://api.___serverHost___/security
paths:
  /statistics/billing-client:
    post:
      tags:
      - Billing Statistics
      summary: Billing Statistics Client
      responses:
        201:
          description: Successful.
          content: {}
      x-codegen-request-body-name: body
      x-contentType: application/json
      x-accepts: application/json
  /resources:
    get:
      tags:
      - Resources
      summary: Get All Resources
      description: Get information about all Resources in your account.
      responses:
        200:
          description: Successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllDDoSResources'
    post:
      tags:
      - Resources
      summary: Create Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDDoSResource'
        required: false
      responses:
        201:
          description: Successful.
          content: {}
      x-codegen-request-body-name: body
  /resources/{resource_id}:
    get:
      tags:
      - Resources
      summary: Get Resource
      parameters:
      - name: resource_id
        in: path
        description: Resource ID.
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Successful.
          content:
            application:
              schema:
                $ref: '#/components/schemas/GetDDoSResource'
    put:
      tags:
      - Resources
      summary: Change Resource
      parameters:
      - name: resource_id
        in: path
        description: Resource ID.
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeDDoSResource'
        required: true
      responses:
        200:
          description: Successful. You will see renewed details of the Resource in
            the response.
          content: {}
      x-codegen-request-body-name: body
    delete:
      tags:
      - Resources
      summary: Delete Resource
      parameters:
      - name: resource_id
        in: path
        description: Resource ID.
        required: true
        schema:
          type: integer
      responses:
        204:
          description: Resource has been deleted successfully
          content: {}
components:
  schemas:
    GetAllDDoSResources:
      type: object
      properties:
        id:
          type: integer
          description: Resource ID.
        enabled:
          type: boolean
          description: The field shows if your Resource is enabled or disabled.<br><ul><li><strong>True</strong>
            &mdash; Resource is active. Content is being delivered.</li><li><strong>False</strong>
            &mdash; Resource is deactivated and content is not being delivered.</li></ul><br>This
            parameter is read only.
        active:
          type: boolean
          description: You can control enabled or disabled state of the Resource by
            setting value for this parameter.
        name:
          type: string
          description: The domain name of the protected resource.
        status:
          type: string
          description: The status of the Resource. <br><br> Active status means that
            your Resources is active. Suspended status means that your trial ended
            or your account is blocked. <br><br>In case of questions contact us at
            ___supportEmail___
        client:
          type: integer
          description: ID of your control panel.
        created:
          type: string
          description: Shows the date when the Resource was created.
        updated:
          type: string
          description: Shows the date when the Resource was changed.
        is_waf_enabled:
          type: boolean
          description: Enable or disable WAF for ddos resource.
        is_redirect_to_https_enabled:
          type: boolean
          description: With this option, all requests through http will be redirected
            to https. Only applied if ssl certificate is provided Value true is used
            by default<br>Available values:<ul><li>true - Enabled</li><li>false -
            Disabled</li></ul>
        service_ip:
          type: string
          description: This is the IP-address which we provide for protection. You
            need to change the A-record for domain/aliases which you want to protect
            on this IP.
        service_botprotect:
          type: integer
          description: This parameter determines whether application-level (L7) protection
            is activated or not.<br>Available values:<ul><li>0 - Disabled</li><li>4
            - Enabled</li></ul>
        ssl_type:
          type: string
          description: Enable or disable using HTTPS with SSL certificate for the
            resource. <br>Available values:<ul><li>null - Disabled</li><li>custom
            - Custom SSL certificate enabled</li><li>le - Let's Encrypt SSL certificate
            enabled</li></ul>To enable custom SSL certificate you should set <strong>service_ssl_crt</strong>
            and <strong>service_ssl_key</strong> parameters.
        service_geoip_mode:
          type: integer
          description: The parameter that determines the access policy for the protected
            resource. Sets up together with <strong>service_geoip_list</strong>. Available
            values:<ul><li>0 - Disabled</li><li>1 - Allow, except list</li><li>2 -
            Deny, except list</li></ul>
        service_geoip_list:
          type: string
          description: This parameter sets up a list of countries for geo restrictions
            for the protected resource. Should be set together with parameter <strong>service_geoip_mode</strong>.
        service_https2http:
          type: integer
          description: With this option, your website can be accessible to users via
            HTTPS, and the connection between the DDoS Protection platform and your
            web server will be via HTTP.<br>Available values:<ul><li>0 - Disabled</li><li>1
            - Enabled</li></ul>
        service_wwwredir:
          type: integer
          description: This parameter allows to set up a redirect from the www.domain.com
            to domain.com. <br>Available values:<ul><li>0 - Disabled</li><li>1 - Enabled</li></ul>
        service_cdn:
          type: integer
          description: For internal use.
        service_cdn_host:
          type: string
          description: For internal use.
        service_cdn_proxy_host:
          type: string
          description: For internal use.
        service_enable:
          type: integer
          description: For internal use.
        service_forcessl:
          type: integer
          description: For internal use.
        service_global_whitelist:
          type: integer
          description: For internal use.
        service_http2:
          type: integer
          description: For internal use.
        service_id:
          type: integer
          description: For internal use.
        service_iphash:
          type: integer
          description: For internal use.
        service_methods:
          type: integer
          description: For internal use.
        service_stream:
          type: integer
          description: For internal use.
        aliases:
          type: object
          properties: {}
          description: These are subdomains that you need to assign to the same protected
            IP.
        origins:
          type: object
          properties: {}
          description: Manually set the web server IPs.
        rate_limier_rules:
          type: object
          properties: {}
          description: Enable rate limiter rules for endpoints
        whitelists:
          type: object
          properties: {}
          description: Sets up as a list of IP addresses.
        blacklists:
          type: object
          properties: {}
          description: Sets up as a list of IP addresses.
      example:
      - id: 1
        name: ddosprotection1.com
        active: true
        client: 2
        enabled: true
        created: 2017-12-01T09:54:46.441966Z
        updated: 2018-12-01T10:21:30.738663Z
        is_waf_enabled: false
        is_redirect_to_https_enabled: true
        status: active
        service_id: 1
        service_ip: 1.2.3.4
        aliases:
        - id: 2
          alias_id: 2
          alias_data: alias1.ddosprotection1.com
          alias_ssl_expire: 0
        - id: 1
          alias_id: 1
          alias_data: alias2.ddosprotection1.com
          alias_ssl_expire: 0
        origins:
        - id: 1
          origin_id: 1
          origin_data: 4.3.2.1
          origin_weight: 50
          origin_mode: primary
        rate_limier_rules:
        - method: GET
          path: helloworld
          value: 2
        - method: POST
          path: api
          value: 10
          test_cookie: false
        - method: GET
          path: docs
          value: 10
          test_cookie: false
        blacklists:
        - id: 10
          blacklist_id: 10
          blacklist_data: 11.111.111.111
        whitelists:
        - id: 10
          whitelist_id: 10
          whitelist_data: 11.111.111.110
        service_https2http: 0
        service_http2: 0
        service_ssl_expire: 0
        service_iphash: 0
        service_enable: 1
        service_geoip_mode: 0
        service_geoip_list: ""
        service_methods: ""
        service_forcessl: 0
        service_wwwredir: 0
        service_cdn: 0
        service_cdn_host: ""
        service_cdn_proxy_host: ""
        service_stream: 0
        service_global_whitelist: 1
    GetDDoSResource:
      type: object
      properties:
        id:
          type: integer
          description: Resource ID.
        enabled:
          type: boolean
          description: The field shows if your Resource is enabled or disabled.<br><ul><li><strong>True</strong>
            &mdash; the Resource is active. Content is being delivered.</li><li><strong>False</strong>
            &mdash; the Resource is deactivated and content is not being delivered.</li></ul><br>This
            parameter is read only.
        active:
          type: boolean
          description: You can control enabled or disabled state of the Resource by
            setting value for this parameter.
        name:
          type: string
          description: The domain name of the protected resource.
        status:
          type: string
          description: The status of the Protection service. <br><br> Active status
            means that your Resources is active. Suspended status means that your
            trial ended or your account is blocked. <br><br>In case of questions contact
            us at ___supportEmail___
        client:
          type: integer
          description: ID of your control panel.
        created:
          type: string
          description: Shows the date when the Resource was created.
        updated:
          type: string
          description: Shows the date when the Resource was changed.
        is_waf_enabled:
          type: boolean
          description: Enable or disable WAF for ddos resource.
        is_redirect_to_https_enabled:
          type: boolean
          description: With this option, all requests through http will be redirected
            to https. Only applied if ssl certificate is provided. Value true is used
            by default<br>Available values:<ul><li>true - Enabled</li><li>false -
            Disabled</li></ul>
        service_ip:
          type: string
          description: This is the IP-address which we provide for protection. You
            need to change the A-record for domain/aliases which you want to protect
            on this IP.
        service_botprotect:
          type: integer
          description: This parameter determines whether application-level (L7) protection
            is activated or not.<br>Available values:<ul><li>0 - Disabled</li><li>4
            - Enabled</li></ul>
        ssl_type:
          type: string
          description: Enable or disable using HTTPS with SSL certificate for the
            resource. <br>Available values:<ul><li>null - Disabled</li><li>custom
            - Custom SSL certificate enabled</li><li>le - Let's Encrypt SSL certificate
            enabled</li></ul>To enable custom SSL certificate you should set <strong>service_ssl_crt</strong>
            and <strong>service_ssl_key</strong> parameters.
        service_geoip_mode:
          type: integer
          description: The parameter that determines the access policy for the protected
            resource. Sets up together with <strong>service_geoip_list</strong>. Available
            values:<ul><li>0 - Disabled</li><li>1 - Allow, except list</li><li>2 -
            Deny, except list</li></ul>
        service_geoip_list:
          type: string
          description: This parameter sets up a list of countries for geo restrictions
            for the protected resource. Should be set together with parameter <strong>service_geoip_mode</strong>.
        service_https2http:
          type: integer
          description: With this option, your website can be accessible to users via
            HTTPS, and the connection between the DDoS Protection platform and your
            web server will be via HTTP.<br>Available values:<ul><li>0 - Disabled</li><li>1
            - Enabled</li></ul>
        service_wwwredir:
          type: integer
          description: This parameter allows to set up a redirect from the www.domain.com
            to domain.com. <br>Available values:<ul><li>0 - Disabled</li><li>1 - Enabled</li></ul>
        service_cdn:
          type: integer
          description: For internal use.
        service_cdn_host:
          type: string
          description: For internal use.
        service_cdn_proxy_host:
          type: string
          description: For internal use.
        service_enable:
          type: integer
          description: For internal use.
        service_forcessl:
          type: integer
          description: For internal use.
        service_global_whitelist:
          type: integer
          description: For internal use.
        service_http2:
          type: integer
          description: For internal use.
        service_id:
          type: integer
          description: For internal use.
        service_iphash:
          type: integer
          description: For internal use.
        service_methods:
          type: integer
          description: For internal use.
        service_stream:
          type: integer
          description: For internal use.
        aliases:
          type: object
          properties: {}
          description: These are subdomains that you need to assign to the same protected
            IP.
        origins:
          type: object
          properties: {}
          description: Manually set the web server IPs.
        rate_limier_rules:
          type: object
          properties: {}
          description: Enable rate limiter rules for endpoints
        whitelists:
          type: object
          properties: {}
          description: Sets up as a list of IP addresses.
        blacklists:
          type: object
          properties: {}
          description: Sets up as a list of IP addresses.
      example:
        id: 1
        name: ddosprotection1.com
        active: true
        client: 2
        enabled: true
        created: 2017-12-01T09:54:46.441966Z
        updated: 2018-12-01T10:21:30.738663Z
        is_waf_enabled: false
        is_redirect_to_https_enabled: true
        status: active
        service_id: 1
        service_ip: 1.2.3.4
        aliases:
        - id: 2
          alias_id: 2
          alias_data: alias1.ddosprotection1.com
          alias_ssl_expire: 0
        - id: 1
          alias_id: 1
          alias_data: alias2.ddosprotection1.com
          alias_ssl_expire: 0
        origins:
        - id: 1
          origin_id: 1
          origin_data: 4.3.2.1
          origin_weight: 50
          origin_mode: primary
        rate_limier_rules:
        - method: GET
          path: helloworld
          value: 2
        - method: POST
          path: api
          value: 10
          test_cookie: false
        - method: GET
          path: docs
          value: 10
          test_cookie: false
        blacklists:
        - id: 10
          blacklist_id: 10
          blacklist_data: 11.111.111.111
        whitelists:
        - id: 10
          whitelist_id: 10
          whitelist_data: 11.111.111.110
        service_botprotect: 0
        service_hsts: 0
        service_waf: "0"
        service_client_id: 2
        service_https2http: 0
        service_http2: 0
        service_ssl_expire: 0
        service_iphash: 0
        service_enable: 1
        service_geoip_mode: 0
        service_geoip_list: ""
        service_methods: ""
        service_forcessl: 0
        service_wwwredir: 0
        service_cdn: 0
        service_cdn_host: ""
        service_cdn_proxy_host: ""
        service_stream: 0
        service_global_whitelist: 1
    ChangeDDoSResource:
      type: object
      properties:
        id:
          type: integer
          description: Resource ID.
        enabled:
          type: boolean
          description: The field shows if your Resource enabled or disabled.<br><ul><li><strong>True</strong>
            &mdash; Resource is actived. Content is being delivered.</li><li><strong>False</strong>
            &mdash; Resource is deactivated and content is not being delivered.</li></ul>This
            parameter is read only.
        active:
          type: boolean
          description: You can control enabled or disabled state of the Resource by
            setting value for this parameter.
        name:
          type: string
          description: The domain name of the protected resource.
        is_waf_enabled:
          type: boolean
          description: Enable or disable WAF for ddos resource.
        is_redirect_to_https_enabled:
          type: boolean
          description: With this option, all requests through http will be redirected
            to https. Only applied if ssl certificate is provided. Value true is used
            by default<br>Available values:<ul><li>true - Enabled</li><li>false -
            Disabled</li></ul>
        status:
          type: string
          description: The status of the Protection service. <br><br> Active status
            means that your Resources is active. Suspended status means that your
            trial ended or your account is blocked. <br><br>In case of questions contact
            us at ___supportEmail___
        client:
          type: integer
          description: ID of your control panel.
        service_ip:
          type: string
          description: Protected IP address. You should set it as A-record for your
            domain name.
        service_botprotect:
          type: integer
          description: Available values:<ul><li>0 - Disabled</li><li>4 - Enabled</li></ul>
        ssl_type:
          type: string
          description: Enable or disable using HTTPS with SSL certificate for the
            resource. <br>Available values:<ul><li>null - Disabled</li><li>custom
            - Custom SSL certificate enabled</li><li>le - Let's Encrypt SSL certificate
            enabled</li></ul>To enable custom SSL certificate you should set <strong>service_ssl_crt</strong>
            and <strong>service_ssl_key</strong> parameters.
        service_ssl_crt:
          type: string
          description: Custom SSL certificate for the Resource.
        service_ssl_key:
          type: string
          description: Private key for custom SSL certificate.
        service_geoip_mode:
          type: integer
          description: The parameter that determines the access policy for the protected
            resource. Sets up together with <strong>service_geoip_list</strong>. Available
            values:<ul><li>0 - Disabled</li><li>1 - Allow, except list</li><li>2 -
            Deny, except list</li></ul>
        service_geoip_list:
          type: string
          description: This parameter sets up a list of countries for geo restrictions
            for the protected resource. Should be set together with parameter <strong>service_geoip_mode</strong>.
        service_https2http:
          type: integer
          description: With this option, your website can be accessible to users via
            HTTPS, and the connection between the DDoS Protection platform and your
            web server will be via HTTP.<br>Available values:<ul><li>0 - Disabled</li><li>1
            - Enabled</li></ul>
        service_wwwredir:
          type: integer
          description: This parameter allows to set up a redirect from the www.domain.com
            to domain.com. <br>Available values:<ul><li>0 - Disabled</li><li>1 - Enabled</li></ul>
        service_cdn:
          type: integer
          description: For internal use.
        service_cdn_host:
          type: string
          description: For internal use.
        service_cdn_proxy_host:
          type: string
          description: For internal use.
        service_enable:
          type: integer
          description: For internal use.
        service_forcessl:
          type: integer
          description: For internal use.
        service_global_whitelist:
          type: integer
          description: For internal use.
        service_http2:
          type: integer
          description: For internal use.
        service_id:
          type: integer
          description: For internal use.
        service_iphash:
          type: integer
          description: For internal use.
        service_methods:
          type: integer
          description: For internal use.
        service_stream:
          type: integer
          description: For internal use.
        created:
          type: string
          description: Shows the date when the Resource was created.
        updated:
          type: string
          description: Shows the date when the Resource was changed.
        aliases:
          type: object
          properties: {}
          description: Aliases for the Resource.
        origins:
          type: object
          properties: {}
          description: Origins for the Resource.
        rate_limier_rules:
          type: object
          properties: {}
          description: Enable rate limiter rules for endpoints
        whitelists:
          type: object
          properties: {}
          description: Whitelists for the Resource.
        blacklists:
          type: object
          properties: {}
          description: Blacklists for the Resource.
      example:
        id: 1
        name: ddosprotection1.com
        active: true
        client: 2
        is_waf_enabled: false
        is_redirect_to_https_enabled: true
        service_botprotect: 0
        service_cdn: 0
        service_cdn_host: ""
        service_cdn_proxy_host: ""
        service_client_id: 2
        service_enable: 1
        service_forcessl: 0
        service_geoip_list: ""
        service_geoip_mode: 0
        service_global_whitelist: 1
        service_hsts: 0
        service_http2: 0
        service_https2http: 0
        service_id: 1
        service_ip: 1.2.3.4
        service_iphash: 0
        service_methods: 0
        service_wwwredir: 0
        service_ssl_crt: "-----BEGIN CERTIFICATE-----\examplecrt\n-----END CERTIFICATE-----"
        service_ssl_key: "-----BEGIN PRIVATE KEY-----\examplekey\n-----END PRIVATE KEY-----\n"
        ssl_type: "custom"
        aliases:
        - id: 2
          alias_id: 2
          alias_data: alias1.ddosprotection1.com
          alias_ssl_expire: 0
        - id: 1
          alias_id: 1
          alias_data: alias2.ddosprotection1.com
          alias_ssl_expire: 0
        origins:
        - id: 1
          origin_id: 1
          origin_data: 4.3.2.1
          origin_weight: 50
          origin_mode: primary
        rate_limier_rules:
        - method: GET
          path: helloworld
          value: 2
        - method: POST
          path: api
          value: 10
          test_cookie: false
        - method: GET
          path: docs
          value: 10
          test_cookie: false
        blacklists:
        - blacklist_data: 11.111.111.111
        whitelists:
        - whitelist_data: 11.111.111.110
    CreateDDoSResource:
      type: object
      properties:
        name:
          type: string
          description: The domain name of the protected resource.
        aliases:
          type: object
          properties: {}
          description: Aliases for the Resource.
        origins:
          type: object
          properties: {}
          description: Origins for the Resource.
        rate_limier_rules:
          type: object
          properties: {}
          description: Enable rate limiter rules for endpoints
        is_waf_enabled:
          type: boolean
          description: Enable or disable WAF for ddos resource.
      example:
        name: ddosprotection1.com
        aliases:
        - alias_data: alias1.ddosprotection1.com
        origins:
        - origin_data: 4.3.2.1
        rate_limier_rules:
        - method: GET
          path: helloworld
          value: 2
        - method: POST
          path: api
          value: 10
          test_cookie: false
        - method: GET
          path: docs
          value: 10
          test_cookie: false
        is_waf_enabled: false